version: '3'

vars:
  APP_NAME: retro-todo-api
  MAIN_PATH: cmd/api/main.go
  MIGRATE_PATH: cmd/migrate/main.go

tasks:
  # dev:
  #   desc: "開発サーバーを起動"
  #   cmds:
  #     - go run {{.MAIN_PATH}}

  # 開発サーバー起動（Air使用）
  dev:
    desc: "開発サーバーを起動（ホットリロード）"
    cmds:
      - air

  # サーバープロセスをkill
  kill:
    desc: "ポート8080のプロセスを停止"
    cmds:
      - lsof -ti :8080 | xargs kill -9 2>/dev/null || echo "No processes to kill"

  # サーバー再起動
  restart:
    desc: "サーバーを再起動（既存プロセスをkill後に起動）"
    cmds:
      - task: kill
      - task: dev

  # ビルド
  build:
    desc: "アプリケーションをビルド"
    cmds:
      - go build -o bin/{{.APP_NAME}} {{.MAIN_PATH}}
    generates:
      - bin/{{.APP_NAME}}

  # マイグレーション実行
  migrate:
    desc: "データベースマイグレーションを実行"
    cmds:
      - go run {{.MIGRATE_PATH}}

  # Swagger関連
  swag:
    desc: "Swaggerドキュメントを生成"
    cmds:
      - swag init -g cmd/api/main.go -o docs --outputTypes go,json,yaml
      - mv docs/swagger.yaml docs/swagger.yml 2>/dev/null || true

  swagger:fmt:
    desc: "Swaggerアノテーションを整形"
    cmds:
      - swag fmt

  # モック生成
  mock:
    desc: "モックファイルを生成（go:generateディレクティブから）"
    cmds:
      - mkdir -p internal/repository/mock
      - mkdir -p internal/handler/mock
      - go generate ./internal/repository/...
      - go generate ./internal/handler/...
      - echo "モックファイルを生成しました"

  # テスト実行
  test:
    desc: "テストを実行"
    cmds:
      - go test -v ./...

  # テストカバレッジ
  test:coverage:
    desc: "テストカバレッジを確認"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "カバレッジレポート coverage.html"

  # 依存関係インストール
  deps:
    desc: "依存関係をインストール"
    cmds:
      - go mod download
      - go mod tidy

  # クリーンアップ
  clean:
    desc: "ビルド成果物を削除"
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  # ============================================
  # Docker関連（Backend個別起動用）
  # ============================================

  start:db:
    desc: "DBのみ起動"
    dir: ..
    cmds:
      - docker compose up postgres -d

  start:be:
    desc: "BackendをDockerで起動"
    dir: ..
    cmds:
      - docker compose up backend -d

  start:
    desc: "DB起動 + Backend起動（ホスト）"
    cmds:
      - task: start:db
      - task: dev

  # ============================================
  # データベース関連
  # ============================================

  db:psql:
    desc: "PostgreSQLに接続"
    dir: ..
    cmds:
      - docker exec -it retro_todo_db psql -U youruser -d retro_todo_db

  db:reset:
    desc: "データベースをリセット"
    dir: ..
    cmds:
      - docker compose down -v
      - docker compose up postgres -d
      - sleep 5
      - cd backend && task migrate
