version: '3'

vars:
  APP_NAME: retro-todo-api
  MAIN_PATH: cmd/api/main.go
  MIGRATE_PATH: cmd/migrate/main.go

tasks:
  # 開発サーバー起動
  dev:
    desc: "開発サーバーを起動"
    cmds:
      - go run {{.MAIN_PATH}}

  # 開発サーバー起動（Air使用）
  dev:watch:
    desc: "開発サーバーを起動（ホットリロード）"
    cmds:
      - air

  # サーバープロセスをkill
  kill:
    desc: "ポート8080のプロセスを停止"
    cmds:
      - lsof -ti :8080 | xargs kill -9 2>/dev/null || echo "No processes to kill"

  # サーバー再起動
  restart:
    desc: "サーバーを再起動（既存プロセスをkill後に起動）"
    cmds:
      - task: kill
      - task: dev

  # ビルド
  build:
    desc: "アプリケーションをビルド"
    cmds:
      - go build -o bin/{{.APP_NAME}} {{.MAIN_PATH}}
    generates:
      - bin/{{.APP_NAME}}

  # マイグレーション実行
  migrate:
    desc: "データベースマイグレーションを実行"
    cmds:
      - go run {{.MIGRATE_PATH}}

  # Swagger関連
  swag:
    desc: "Swaggerドキュメントを生成"
    cmds:
      - swag init -g cmd/api/main.go -o docs --outputTypes go,json,yaml
      - mv docs/swagger.yaml docs/swagger.yml 2>/dev/null || true

  swagger:fmt:
    desc: "Swaggerアノテーションを整形"
    cmds:
      - swag fmt

  # テスト実行
  test:
    desc: "テストを実行"
    cmds:
      - go test -v ./...

  # テストカバレッジ
  test:coverage:
    desc: "テストカバレッジを確認"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "カバレッジレポート coverage.html"

  # 依存関係インストール
  deps:
    desc: "依存関係をインストール"
    cmds:
      - go mod download
      - go mod tidy

  # クリーンアップ
  clean:
    desc: "ビルド成果物を削除"
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  # Docker関連
  docker:up:
    desc: "Dockerコンテナを起動"
    dir: ..
    cmds:
      - docker compose up -d

  docker:down:
    desc: "Dockerコンテナを停止"
    dir: ..
    cmds:
      - docker compose down

  docker:restart:
    desc: "Dockerコンテナを再起動"
    dir: ..
    cmds:
      - docker compose restart

  docker:clean:
    desc: "Dockerコンテナとボリュームを削除"
    dir: ..
    cmds:
      - docker compose down -v

  # データベース関連
  db:psql:
    desc: "PostgreSQLに接続"
    cmds:
      - docker exec -it retro_todo_db psql -U youruser -d retro_todo_db

  db:reset:
    desc: "データベースをリセット"
    cmds:
      - task: docker:clean
      - task: docker:up
      - sleep 3
      - task: migrate

  # 開発環境セットアップ
  setup:
    desc: "開発環境をセットアップ"
    cmds:
      - task: deps
      - task: docker:up
      - sleep 3
      - task: migrate
      - echo 'セットアップ完了！'

  # サーバー起動（フル）
  start:
    desc: "フルスタックで起動（Docker + API）"
    cmds:
      - task: docker:up
      - sleep 3
      - task: migrate
      - task: dev

  # ヘルプ
  help:
    desc: "利用可能なタスクを表示"
    cmds:
      - task --list