// Code generated by MockGen. DO NOT EDIT.
// Source: todo_handler.go
//
// Generated by this command:
//
//	mockgen -source=todo_handler.go -destination=mock/mock_todo_handler.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoHandlerInterface is a mock of TodoHandlerInterface interface.
type MockTodoHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTodoHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockTodoHandlerInterfaceMockRecorder is the mock recorder for MockTodoHandlerInterface.
type MockTodoHandlerInterfaceMockRecorder struct {
	mock *MockTodoHandlerInterface
}

// NewMockTodoHandlerInterface creates a new mock instance.
func NewMockTodoHandlerInterface(ctrl *gomock.Controller) *MockTodoHandlerInterface {
	mock := &MockTodoHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockTodoHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoHandlerInterface) EXPECT() *MockTodoHandlerInterfaceMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoHandlerInterface) CreateTodo(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoHandlerInterfaceMockRecorder) CreateTodo(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoHandlerInterface)(nil).CreateTodo), c)
}

// DeleteTodo mocks base method.
func (m *MockTodoHandlerInterface) DeleteTodo(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoHandlerInterfaceMockRecorder) DeleteTodo(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoHandlerInterface)(nil).DeleteTodo), c)
}

// GetTodos mocks base method.
func (m *MockTodoHandlerInterface) GetTodos(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodos", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetTodos indicates an expected call of GetTodos.
func (mr *MockTodoHandlerInterfaceMockRecorder) GetTodos(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodos", reflect.TypeOf((*MockTodoHandlerInterface)(nil).GetTodos), c)
}

// SearchTodos mocks base method.
func (m *MockTodoHandlerInterface) SearchTodos(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTodos", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SearchTodos indicates an expected call of SearchTodos.
func (mr *MockTodoHandlerInterfaceMockRecorder) SearchTodos(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTodos", reflect.TypeOf((*MockTodoHandlerInterface)(nil).SearchTodos), c)
}

// UpdateTodo mocks base method.
func (m *MockTodoHandlerInterface) UpdateTodo(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoHandlerInterfaceMockRecorder) UpdateTodo(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoHandlerInterface)(nil).UpdateTodo), c)
}
