// Code generated by MockGen. DO NOT EDIT.
// Source: sprint_handler.go
//
// Generated by this command:
//
//	mockgen -source=sprint_handler.go -destination=mock/mock_sprint_handler.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockSprintHandlerInterface is a mock of SprintHandlerInterface interface.
type MockSprintHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSprintHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockSprintHandlerInterfaceMockRecorder is the mock recorder for MockSprintHandlerInterface.
type MockSprintHandlerInterfaceMockRecorder struct {
	mock *MockSprintHandlerInterface
}

// NewMockSprintHandlerInterface creates a new mock instance.
func NewMockSprintHandlerInterface(ctrl *gomock.Controller) *MockSprintHandlerInterface {
	mock := &MockSprintHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockSprintHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSprintHandlerInterface) EXPECT() *MockSprintHandlerInterfaceMockRecorder {
	return m.recorder
}

// CreateSprint mocks base method.
func (m *MockSprintHandlerInterface) CreateSprint(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSprint", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSprint indicates an expected call of CreateSprint.
func (mr *MockSprintHandlerInterfaceMockRecorder) CreateSprint(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSprint", reflect.TypeOf((*MockSprintHandlerInterface)(nil).CreateSprint), c)
}

// DeleteSprint mocks base method.
func (m *MockSprintHandlerInterface) DeleteSprint(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSprint", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSprint indicates an expected call of DeleteSprint.
func (mr *MockSprintHandlerInterfaceMockRecorder) DeleteSprint(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSprint", reflect.TypeOf((*MockSprintHandlerInterface)(nil).DeleteSprint), c)
}

// GetSprints mocks base method.
func (m *MockSprintHandlerInterface) GetSprints(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSprints", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetSprints indicates an expected call of GetSprints.
func (mr *MockSprintHandlerInterfaceMockRecorder) GetSprints(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSprints", reflect.TypeOf((*MockSprintHandlerInterface)(nil).GetSprints), c)
}

// SearchSprints mocks base method.
func (m *MockSprintHandlerInterface) SearchSprints(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSprints", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// SearchSprints indicates an expected call of SearchSprints.
func (mr *MockSprintHandlerInterfaceMockRecorder) SearchSprints(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSprints", reflect.TypeOf((*MockSprintHandlerInterface)(nil).SearchSprints), c)
}

// UpdateSprint mocks base method.
func (m *MockSprintHandlerInterface) UpdateSprint(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSprint", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSprint indicates an expected call of UpdateSprint.
func (mr *MockSprintHandlerInterfaceMockRecorder) UpdateSprint(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSprint", reflect.TypeOf((*MockSprintHandlerInterface)(nil).UpdateSprint), c)
}
