// Code generated by MockGen. DO NOT EDIT.
// Source: auth_handler.go
//
// Generated by this command:
//
//	mockgen -source=auth_handler.go -destination=mock/mock_auth_handler.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthHandlerInterface is a mock of AuthHandlerInterface interface.
type MockAuthHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthHandlerInterfaceMockRecorder is the mock recorder for MockAuthHandlerInterface.
type MockAuthHandlerInterfaceMockRecorder struct {
	mock *MockAuthHandlerInterface
}

// NewMockAuthHandlerInterface creates a new mock instance.
func NewMockAuthHandlerInterface(ctrl *gomock.Controller) *MockAuthHandlerInterface {
	mock := &MockAuthHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHandlerInterface) EXPECT() *MockAuthHandlerInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthHandlerInterface) Login(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockAuthHandlerInterfaceMockRecorder) Login(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthHandlerInterface)(nil).Login), c)
}

// Register mocks base method.
func (m *MockAuthHandlerInterface) Register(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAuthHandlerInterfaceMockRecorder) Register(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthHandlerInterface)(nil).Register), c)
}
