// Code generated by MockGen. DO NOT EDIT.
// Source: sprint_repository.go
//
// Generated by this command:
//
//	mockgen -source=sprint_repository.go -destination=mock/mock_sprint_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	model "backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSprintRepository is a mock of SprintRepository interface.
type MockSprintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSprintRepositoryMockRecorder
	isgomock struct{}
}

// MockSprintRepositoryMockRecorder is the mock recorder for MockSprintRepository.
type MockSprintRepositoryMockRecorder struct {
	mock *MockSprintRepository
}

// NewMockSprintRepository creates a new mock instance.
func NewMockSprintRepository(ctrl *gomock.Controller) *MockSprintRepository {
	mock := &MockSprintRepository{ctrl: ctrl}
	mock.recorder = &MockSprintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSprintRepository) EXPECT() *MockSprintRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSprintRepository) Create(title string) (*model.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", title)
	ret0, _ := ret[0].(*model.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSprintRepositoryMockRecorder) Create(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSprintRepository)(nil).Create), title)
}

// Delete mocks base method.
func (m *MockSprintRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSprintRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSprintRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockSprintRepository) FindAll() ([]model.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSprintRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSprintRepository)(nil).FindAll))
}

// Search mocks base method.
func (m *MockSprintRepository) Search(req *model.SprintSearchRequest) ([]model.Sprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", req)
	ret0, _ := ret[0].([]model.Sprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSprintRepositoryMockRecorder) Search(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSprintRepository)(nil).Search), req)
}

// Update mocks base method.
func (m *MockSprintRepository) Update(id int, title string, completed bool) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, title, completed)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockSprintRepositoryMockRecorder) Update(id, title, completed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSprintRepository)(nil).Update), id, title, completed)
}
